### ISSUE TITLE
The speed of training

### ISSUE THREAD

**Issue by super233** [lorenmt/reco#11]
Hi, thanks for your sharing code, it's awesome work.

I'm a green hand in contrastive learning, I'm running your code with an NVIDIA Tesla T4, but it seems slowly for training and the GPU-Util can not always keep a value that is greater than 50%, is it a normal phenomenon?

It seems that the process of selecting queries and corresponding negative keys is time consuming.

**Comment by lorenmt** [comment]
Hello,

Yes, since ReCo samples hard pixels and accumulates losses across all semantic classes, this is a common observation. You may speed up training by sampling a lower number of queries.
