### ISSUE TITLE
question about Ablative Analysis

### ISSUE THREAD

**Issue by wwjwy** [lorenmt/reco#15]
Hi, 
In Section 4.4 Ablative Analysis, the Effect of Active Sampling was verified. Could you please tell me how to conduct (Random Query,Random Key ) and other settings?
Thanks!

**Comment by lorenmt** [comment]
Hello!

That's fairly simple. Using a very large temperature via `--temp 100` for example, will roughly give a uniform sampling, i.e. random key sampling. Using a very low weak threshold and a very large strong threshold via `--weak_threshold 0.0, --strong_threshold 1.0` will then sample all pixels as query, i.e. random query sampling.

Hope that helps.

**Comment by wwjwy** [comment]
Thank you very much! can you tell me how to realize Easy Query? other settings i have understand your meaning.

**Comment by lorenmt** [comment]
Change: https://github.com/lorenmt/reco/blob/265cd2c97b8bf5dda461034f1dd08e4fb75c5c1e/module_list.py#L87
into > strong threshold

**Comment by wwjwy** [comment]
> Change:
> 
> https://github.com/lorenmt/reco/blob/265cd2c97b8bf5dda461034f1dd08e4fb75c5c1e/module_list.py#L87
> 
> 
> into > strong threshold

Does the strong_threshold should  keep the original setting(0.97)?

**Comment by lorenmt** [comment]
Yes.

**Comment by wwjwy** [comment]
Thank you very much for your timely help!
