### ISSUE TITLE
Where is the test code?

### ISSUE THREAD

**Issue by TyroneLi** [lorenmt/reco#2]
Where is the test code? Could u release this part. By the way, do u consider compute the reco loss across the whole dataset or the past few mini-batch instead of the current mini-batch.

**Comment by lorenmt** [comment]
> > Hello, the released code already includes testing and every component to reproduce the results in the paper. Could you specify which other implementation you need?
> > The reco loss is only computed by the current batch for simplicity. And it actually works the best compared to the whole dataset/history batch in my own experience.
> 
> So you have already tried using the whole dataset/ history batch to compute reco loss? Why don't u just update this part code?

As I said, the current implementation achieves higher performance compared to using the whole dataset.
