### ISSUE TITLE
ASPPPooling issue

### ISSUE THREAD

**Issue by fred-xue** [lorenmt/reco#21]
Thanks for your code. I'm exploring your code, and ran into an issue with the line below. Seems not right. I'm on pytorch 1.10. 

https://github.com/lorenmt/reco/blob/71c1b7324fd36049c6657b122ba3fef373877b72/network/deeplabv3/aspp.py#L37

**Comment by lorenmt** [comment]
Hello, I have tested all of the code with pytorch 1.7 before open-sourcing. So it might be from the version issue.

What's the exact problem you were facing?

**Comment by fred-xue** [comment]
thanks for the reply. It's my mistake in testing with a batch size of 1
