### ISSUE TITLE
how to apply reco loss to supervised segmentation

### ISSUE THREAD

**Issue by hxshust** [lorenmt/reco#24]

**Comment by lorenmt** [comment]
I thought train_sup.py should give an example on this?

**Comment by hxshust** [comment]
Hi，thanks for sharing your impressive code.
As I see in your object page, 
`ReCo can easily be added to modern supervised and semi-supervised segmentation methods without changing the training pipeline, with no additional cost at inference time. To incorporate ReCo, we simply add an additional representation head on top of the feature encoder of a segmentation network, and apply the ReCo loss to this representation using the active sampling strategy.`

**Comment by hxshust** [comment]
without additional modifications to the network structure？I thought an extra branch was needed, outside the segmented branch, use the encoder's feature vector with the ground truth to calculate the reco loss

**Comment by hxshust** [comment]
thanks anyway，I will check the train_sup.py again，: ）
