### ISSUE TITLE
Number of Queries and keys

### ISSUE THREAD

**Issue by wwjwy** [lorenmt/reco#25]
再次打扰一下作者，请问消融研究中的Number of Queries  and keys，keys数量选择指的是负样本（r k-）的数量吗？
还有就是消融研究中query-key数量研究是怎么进行的呢，比如query依次选择32 64 128 256 时，对应的key数量是固定值吗？如果是固定为多少呢？谢谢！

**Comment by lorenmt** [comment]
对，只改一个参数剩下的是 默认。默认参数定义在python file 里。

**Comment by wwjwy** [comment]
明白了，谢谢您！

**Comment by wwjwy** [comment]
最终选择的结果为query256  key512最优，可以发现需要更多的key，可以理解为因为与其他类别进行对比学习时需要更多的负样本点用来对比吗？

**Comment by lorenmt** [comment]
这只是超参而已 不用过度解读

**Comment by wwjwy** [comment]
好的好的
