### ISSUE TITLE
error in pascal_preprocess.py

### ISSUE THREAD

**Issue by volare1996** [lorenmt/reco#26]
The following error occurred while running the preprocessing script.
`im = np.array(Image.open(label_list[i])

OSError:codec configuration  error when reading image file`

**Comment by lorenmt** [comment]
I believe that's a package-specific issue. Maybe try upgrade pillow as suggested from here? https://stackoverflow.com/questions/42462431/oserror-broken-data-stream-when-reading-image-file

Or alternatively, you may directly download the pre-processed dataset which also linked in readme.

**Comment by volare1996** [comment]
Thanks for your reply. I'll have a try.
