### ISSUE TITLE
About query samples and key samples setting.

### ISSUE THREAD

**Issue by DISAPPEARED13** [lorenmt/reco#28]
Thanks for inspiring work! 

I notice that in part _Implementation Details_ , you mention that in ReCo framework, you sampled 256 query samples and 512 key samples for each mini-batch, could you please tell me why is 256 and 512? 

Thanks a lot!

**Comment by lorenmt** [comment]
That's purely empirical. You may check out the ablative analysis section to see the performance of other sample numbers.

**Comment by DISAPPEARED13** [comment]
Thanks for replying! I am confused that the sample numbers should have been related with the input patch pixels number. For enough points seems play a very important role when caculating the reco loss :smile: 
So is it the reason when you chose `number of queries` and `number of keys`?

**Comment by lorenmt** [comment]
Strictly speaking yes. But it works well in practise which I assume mainly because of the design of active sampling.
