### ISSUE TITLE
About the gradient flow in contrastive learning

### ISSUE THREAD

**Issue by gavinwxy** [lorenmt/reco#30]
I notice that you do not apply detach operation when you do contrastive learning, which means the loss gradient applies on both query and keys. I was wondering if this is a common practice because in other works based on contrastive learning, the gradients only flow through query samples. Does it make any difference on training? Any hints will be appreciated.

**Comment by lorenmt** [comment]
https://github.com/lorenmt/reco/blob/71c1b7324fd36049c6657b122ba3fef373877b72/module_list.py#L112 No gradients were flowed through keys.

**Comment by gavinwxy** [comment]
Thanks for the reply
