### ISSUE TITLE
关于类别关系矩阵的更新

### ISSUE THREAD

**Issue by ck6698000** [lorenmt/reco#32]
根据代码来看，这个用于sample的矩阵是每次batch单独计算是吗？不知道我理解的对吗
我原以为会记录一个小的bank保存各个类的特征平均值，每次迭代更新这个值呢。然后用维护的类特征向量不断计算新的相似矩阵

**Comment by ck6698000** [comment]
话说你们的PDF真是大T_T

**Comment by lorenmt** [comment]
> 根据代码来看，这个用于sample的矩阵是每次batch单独计算是吗？不知道我理解的对吗 我原以为会记录一个小的bank保存各个类的特征平均值，每次迭代更新这个值呢。然后用维护的类特征向量不断计算新的相似矩阵

对的. 如果用一个bank的话 计算量就会很大 因为需要存储数据集里定义的所有类别, 里面很多计算就会冗余. 一个简单的例子, 飞机和花肯定不会混淆, 也很少出现在同一张图片里, 所以用一个bank 计算就没必要.

**Comment by ck6698000** [comment]
> > 根据代码来看，这个用于sample的矩阵是每次batch单独计算是吗？不知道我理解的对吗 我原以为会记录一个小的bank保存各个类的特征平均值，每次迭代更新这个值呢。然后用维护的类特征向量不断计算新的相似矩阵
> 
> 对的. 如果用一个bank的话 计算量就会很大 因为需要存储数据集里定义的所有类别, 里面很多计算就会冗余. 一个简单的例子, 飞机和花肯定不会混淆, 也很少出现在同一张图片里, 所以用一个bank 计算就没必要.

ok 谢谢解答
