### ISSUE TITLE
Questions about train_u_label

### ISSUE THREAD

**Issue by sang2232** [lorenmt/reco#35]
Hello, I am a student studying deep learning.
In the code below, I know that train_u_dataset is a data set without label.
I wonder what train_u_label is and why it is necessary.

        train_u_data, train_u_label = train_u_dataset.next()
        train_u_data, train_u_label = train_u_data.to(device), train_u_label.to(device)

Thank you for your wonderful code.

**Comment by lorenmt** [comment]
Hello. These labels are defined in the original dataset, we just don't use them as part of the training. But we can evaluate the quality of generated labels compared to the ground-truth labels. Hope that helps.

**Comment by sang2232** [comment]
Thank you for your kind reply.

I understand.
