### ISSUE TITLE
Random Seed for cityscape

### ISSUE THREAD

**Issue by ChandayHunt** [lorenmt/reco#36]
Hello author,
Thank you for your work. I have used the provided code to reproduce the results of cityscape with label 20. I tried the following python command:

```
python train_semisup.py \
--dataset cityscapes \
--num_labels 20 \
--apply_aug classmix \
--apply_reco \
--seed 0
```

and I chose `--seed` from `0, 1 and 2`, however the results that I got were around 45% IOU. Could you please share your random seed for inference please? And if you find the command wrong, please correct me.

Thank you!

**Comment by lorenmt** [comment]
Hi, this looks correct. However, I also found the performance might vary across different machines...might due to different versions of dependencies or so. But the ranking stays the same, the issue will be alleviated with a larger amount of labelled images.

**Comment by ChandayHunt** [comment]
Yeah that is true. I haven't tried other methods in the table but it's really weird that the IOU didn't reach 49. Anyway thank you for sharing.
