### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by yjq767579182** [lorenmt/reco#40]
Hello, I want to ask the following problem, I know the solution      train_l_data, train_l_label = train_l_dataset.next()
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

**Comment by lorenmt** [comment]
Hello, sorry I don't understand your question. Are you doing multi-gpu training?

**Comment by yjq767579182** [comment]
thanks for your reply  I trained the model with a single GPU  I have solved the problem

**Comment by JiabaoChen1** [comment]
> thanks for your reply I trained the model with a single GPU I have solved the problem

hello，I want to know how you do it
