### ISSUE TITLE
Question about the contrastive loss

### ISSUE THREAD

**Issue by Hugo-cell111** [lorenmt/reco#42]
Hi! may you provide the training log of the experiment? I want to see the convergence curve of contrastive loss. Because the implemented contrastive loss by myself borrows largely from your code but drops very slightly, I am afraid I might make some mistakes. Thanks a lot!

**Comment by lorenmt** [comment]
Hi, sorry that I did not record any training logs. But I would suggest having some generated pseudo images for testing. The contrastive loss simply would not go down to a very low value.

**Comment by Hugo-cell111** [comment]
Yes, the contrastive loss wouldn't go down to a very low value. But my loss has gone down very slightly(from about 3.84 to 3.8), and I wonder if you have met such situation. Thanks!










 
 
 ----------Reply to Message----------
 On Mon, Oct 2, 2023 00:59 AM Shikun ***@***.***&gt; wrote:

  

 
Hi, sorry that I did not record any training logs. But I would suggest having some generated pseudo images for testing. The contrastive loss simply would not go down to a very low value.

**Comment by lorenmt** [comment]
I think you should measure by the validation performance instead of the training loss which does not reflect the true model's performance.
