### ISSUE TITLE
reco损失计算时负样本如何只针对特定类别进行采样

### ISSUE THREAD

**Issue by wade0604** [lorenmt/reco#43]
您好！
我想请教下您，我现在有9个类别，其中有几个类别的表现不是特别好，我想在计算reco损失的时候只针对这些表现不好的类别进行负样本采样，请问这个应该怎么实现

**Comment by lorenmt** [comment]
你是指这只再这几个样本做loss 还是对所有样本做loss但是负采样只采这几个样本?

**Comment by lorenmt** [comment]
No further updates.
