### ISSUE TITLE
将roco迁移到医学图像分割

### ISSUE THREAD

**Issue by JiabaoChen1** [lorenmt/reco#44]
您好！我想请教一下您，我将您的模型迁移到医学图像分割（只有两类），在给少量标注的情况下，去掉对比学习比加上对比学习的效果都要好，我也尝试了改进方法，但是效果都不好，想请问您有什么见解吗？

**Comment by lorenmt** [comment]
如果只有两类那根本没有加对比学习的必要吧？？这只会overfitting

**Comment by JiabaoChen1** [comment]
> 如果只有两类那根本没有加对比学习的必要吧？？这只会overfitting

感谢您的回复！我只给大概15%instance，只用半监督还是达不到一个很好的效果，希望用对比学习学到一些监督和半监督学不到的东西。

**Comment by lorenmt** [comment]
ok. 这同样也取决于有label的数据质量和没有label的数据质量。。当然通常来说class越少，这些方法的提升也就越少，但至少不会取反作用。你可以在ReCo的citation里翻下，有相当多应用在medical domain的一些文章，可以参看他们是否做了一些改动。。但抱歉我无法提供更多帮助。

**Comment by JiabaoChen1** [comment]
好的，谢谢您
