### ISSUE TITLE
关于用于对比学习的representation head

### ISSUE THREAD

**Issue by Secret813** [lorenmt/reco#45]
您好，我想请问一下是将用于对比学习的特征映射头具体添加到什么位置了呢？是在deeplabv3的代码中吗，我没有找到这部分代码。

**Comment by lorenmt** [comment]
https://github.com/lorenmt/reco/blob/71c1b7324fd36049c6657b122ba3fef373877b72/network/deeplabv3/deeplabv3.py#L43

**Comment by Secret813** [comment]
谢谢您！
