### ISSUE TITLE
Request for the code of DeepLab V2.

### ISSUE THREAD

**Issue by super233** [lorenmt/reco#5]
Hi, thanks for your sharing code, it's really an awesome work!

Can you release the code of DeepLabe V2 which contains the projector? There's only code of DeepLab V3.

Currently I'm studying the contrastive learning based on DeepLabe V2, if you can provide the corresponding code for my reference, it will really appreciate.

**Comment by lorenmt** [comment]
Hello,

I have updated the DeepLabv2 code. You may use flag `--backbone deeplabv2` on the training script to switch to the DeepLabv2 backbone. Please note that deeplabv2 would run slower and achieve worse performance compared to DeepLabv3+ (the default option).

I haven't fully re-tested the results for DeepLabv2, so please let me know if you find any unusual behavior. :)

**Comment by super233** [comment]
Ok, thanks very much! 👍

**Comment by super233** [comment]
Hi, I have run your code with DeepLab V2 and DeepLab V3+ respectively on Cityscapes where only 20 images have labels.

However, the ReCo with DeepLab V3+ only has the best performance of 48.76, which is slightly worse than 49.86±0.28 reported in your paper. What's more, the ReCo with DeepLab V2 has a better performance of 50.51.

Is this a normal phenomenon? I only run your code with the following commands and not do any modification to code:
```bash
python train_semisup.py --dataset cityscapes --num_labels 20 --apply_aug classmix --apply_reco --backbone deeplabv3p
python train_semisup.py --dataset cityscapes --num_labels 20 --apply_aug classmix --apply_reco --backbone deeplabv2
```

**Comment by lorenmt** [comment]
Hello, yes that's perfectly normal. With as few as 20 labelled images, the performance can be a bit unstable. +-2% would be in a reasonable range.

**Comment by super233** [comment]
Ok, thanks. :-)

**Comment by super233** [comment]
I'm sorry to disturb you again, there seems an extra indent in `return out`, is it a typo or for some purpose?
https://github.com/lorenmt/reco/blob/3e856a316cd082f2e84bd3972d5f6c5fe24254bd/network/deeplabv2.py#L16-L20

**Comment by lorenmt** [comment]
good catch! it's a typo indeed.

**Comment by super233** [comment]
Ok, thanks. :-)
